services:

  mysql:
    image: navyasrig/project_prod:dbimage
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    ports:
      - "5555:3306"
    networks:
      - sql_network
      - quiz_network
    volumes:
      - mysql:/mysql/navya/
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: employeedb
      MYSQL_USER: navya

  quiz:
    image: navyasrig/project_prod:appimage
    environment:
     DB_URL: jdbc:mysql://mysql:3306/quiz_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
     DB_USER: root
     DB_PASSWORD: 1234
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    ports:
      - "1111:8080"
    networks:
      - quiz_network
      - sql_network
    volumes:
      - quiz:/quiz/navya/
    depends_on:
      - "mysql"

networks:
  quiz_network:
    driver: overlay

  sql_network:
    driver: overlay

volumes:
  mysql:
  quiz:

secrets:
  MYSQL_ROOT_PASSWORD:
    external: true

  MYSQL_PASSWORD:
    external: true
