services:

   mysql:
    container_name: mysql
    image: navyasrig/prod:dbimage
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    ports:
      - "5555:3306"
    networks:
      - sql_network
      - quiz_network
    volumes:
      - mysql:/mysql/navya/
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: employeedb
      MYSQL_USER: navya

  quiz:
    container_name: quiz
    image: navyasrig/prod:appimage
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
        reservations:
          cpus: "0.25"
          memory: 64M
    restart: unless-stopped
    ports:
      - "4444:8080"
    networks:
      - quiz_network
      - sql_network
    volumes:
      - quiz:/quiz/navya/



networks:
  quiz_network:
    driver: overlay
  sql_network:
    driver: overlay

volumes:
  mysql:
  quiz:

secrets:
  MYSQL_ROOT_PASSWORD:
    external: true

  MYSQL_PASSWORD:
    external: true
