USE quiz_db;

-- Insert sample users (password is 'password123' - hashed with BCrypt)
-- Note: These are BCrypt hashes for 'password123'
INSERT INTO users (username, email, password_hash) VALUES
('john_doe', 'john@example.com', '$2a$10$rV3ZqHkXqXqXqXqXqXqXqOeXqXqXqXqXqXqXqXqXqXqXqXqXq'),
('jane_smith', 'jane@example.com', '$2a$10$rV3ZqHkXqXqXqXqXqXqXqOeXqXqXqXqXqXqXqXqXqXqXqXqXq'),
('admin_user', 'admin@example.com', '$2a$10$rV3ZqHkXqXqXqXqXqXqXqOeXqXqXqXqXqXqXqXqXqXqXqXqXq');

-- Insert 50 questions
INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_answer, category, difficulty) VALUES
('What is the capital of France?', 'London', 'Berlin', 'Paris', 'Madrid', 'C', 'Geography', 'Easy'),
('Which programming language is known for its "write once, run anywhere" capability?', 'Python', 'C++', 'Java', 'JavaScript', 'C', 'Programming', 'Easy'),
('What is 15 + 27?', '40', '42', '41', '43', 'B', 'Mathematics', 'Easy'),
('Who painted the Mona Lisa?', 'Van Gogh', 'Picasso', 'Da Vinci', 'Rembrandt', 'C', 'Art', 'Medium'),
('What is the largest ocean on Earth?', 'Atlantic', 'Indian', 'Arctic', 'Pacific', 'D', 'Geography', 'Easy'),
('Which year did World War II end?', '1943', '1944', '1945', '1946', 'C', 'History', 'Medium'),
('What is the chemical symbol for Gold?', 'Go', 'Gd', 'Au', 'Ag', 'C', 'Science', 'Easy'),
('Who wrote "Romeo and Juliet"?', 'Charles Dickens', 'Jane Austen', 'William Shakespeare', 'Mark Twain', 'C', 'Literature', 'Easy'),
('What is the square root of 144?', '10', '11', '12', '13', 'C', 'Mathematics', 'Easy'),
('Which planet is known as the Red Planet?', 'Jupiter', 'Mars', 'Venus', 'Saturn', 'B', 'Science', 'Easy'),
('What is the fastest land animal?', 'Lion', 'Cheetah', 'Leopard', 'Tiger', 'B', 'Animals', 'Easy'),
('Who invented the telephone?', 'Edison', 'Tesla', 'Bell', 'Newton', 'C', 'History', 'Medium'),
('What is the boiling point of water at sea level?', '90°C', '95°C', '100°C', '105°C', 'C', 'Science', 'Easy'),
('Which country gifted the Statue of Liberty to the USA?', 'England', 'Spain', 'France', 'Germany', 'C', 'History', 'Medium'),
('What is the national sport of Japan?', 'Baseball', 'Karate', 'Judo', 'Sumo', 'D', 'Sports', 'Hard'),
('Who painted the Sistine Chapel ceiling?', 'Donatello', 'Raphael', 'Michelangelo', 'Leonardo', 'C', 'Art', 'Hard'),
('What is the capital of Japan?', 'Seoul', 'Beijing', 'Bangkok', 'Tokyo', 'D', 'Geography', 'Easy'),
('Which element has the chemical symbol O?', 'Gold', 'Oxygen', 'Osmium', 'Silver', 'B', 'Science', 'Easy'),
('Who wrote "1984"?', 'Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'Ernest Hemingway', 'B', 'Literature', 'Medium'),
('What is the longest river in the world?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 'B', 'Geography', 'Medium'),
('Which programming language is primarily used for Android development?', 'Swift', 'Kotlin', 'Python', 'Ruby', 'B', 'Programming', 'Medium'),
('Who discovered penicillin?', 'Curie', 'Pasteur', 'Fleming', 'Koch', 'C', 'Science', 'Hard'),
('What is the smallest prime number?', '0', '1', '2', '3', 'C', 'Mathematics', 'Easy'),
('Which actor played Iron Man?', 'Chris Evans', 'Chris Hemsworth', 'Robert Downey Jr', 'Scarlett Johansson', 'C', 'Entertainment', 'Easy'),
('What is the currency of the United Kingdom?', 'Euro', 'Dollar', 'Pound', 'Yen', 'C', 'General', 'Easy'),
('Who developed the theory of relativity?', 'Newton', 'Galileo', 'Einstein', 'Hawking', 'C', 'Science', 'Medium'),
('What is the tallest mountain in the world?', 'K2', 'Kangchenjunga', 'Everest', 'Makalu', 'C', 'Geography', 'Easy'),
('Which company created Windows OS?', 'Apple', 'Google', 'IBM', 'Microsoft', 'D', 'Technology', 'Easy'),
('What is the primary color of a clear sky?', 'Green', 'Yellow', 'Red', 'Blue', 'D', 'General', 'Easy'),
('Who sang "Thriller"?', 'Prince', 'Madonna', 'Michael Jackson', 'Whitney Houston', 'C', 'Music', 'Medium'),
('What is the hardest natural substance?', 'Iron', 'Gold', 'Diamond', 'Platinum', 'C', 'Science', 'Easy'),
('Which country is known as the Land of the Rising Sun?', 'China', 'Korea', 'Japan', 'Thailand', 'C', 'Geography', 'Easy'),
('Who painted the Starry Night?', 'Picasso', 'Monet', 'Van Gogh', 'Degas', 'C', 'Art', 'Medium'),
('What is the main ingredient in guacamole?', 'Tomato', 'Onion', 'Avocado', 'Lime', 'C', 'Food', 'Easy'),
('Which sport is known as "the beautiful game"?', 'Basketball', 'Cricket', 'Football', 'Tennis', 'C', 'Sports', 'Easy'),
('Who wrote "The Lord of the Rings"?', 'J.K. Rowling', 'George R.R. Martin', 'J.R.R. Tolkien', 'C.S. Lewis', 'C', 'Literature', 'Medium'),
('What is the capital of Brazil?', 'Rio de Janeiro', 'Sao Paulo', 'Brasilia', 'Salvador', 'C', 'Geography', 'Hard'),
('Which animal is known as the "Ship of the Desert"?', 'Horse', 'Camel', 'Elephant', 'Lion', 'B', 'Animals', 'Easy'),
('Who directed the movie "Inception"?', 'James Cameron', 'Steven Spielberg', 'Christopher Nolan', 'Quentin Tarantino', 'C', 'Entertainment', 'Medium'),
('What is the chemical formula for water?', 'CO2', 'O2', 'H2O', 'NaCl', 'C', 'Science', 'Easy'),
('Which country hosted the 2016 Olympics?', 'London', 'Rio de Janeiro', 'Tokyo', 'Beijing', 'B', 'Sports', 'Medium'),
('Who wrote "Pride and Prejudice"?', 'Emily Bronte', 'Jane Austen', 'Charles Dickens', 'George Eliot', 'B', 'Literature', 'Medium'),
('What is the largest desert in the world?', 'Gobi', 'Sahara', 'Arabian', 'Antarctic', 'D', 'Geography', 'Hard'),
('Which band performed "Bohemian Rhapsody"?', 'The Beatles', 'Queen', 'Led Zeppelin', 'Pink Floyd', 'B', 'Music', 'Medium'),
('What is the powerhouse of the cell?', 'Nucleus', 'Mitochondria', 'Ribosome', 'Golgi', 'B', 'Science', 'Medium'),
('Who was the first person to walk on the moon?', 'Buzz Aldrin', 'Neil Armstrong', 'Michael Collins', 'Yuri Gagarin', 'B', 'History', 'Easy'),
('What is the national flower of Japan?', 'Rose', 'Lotus', 'Cherry Blossom', 'Orchid', 'C', 'Culture', 'Medium'),
('Which company is known for the iPhone?', 'Samsung', 'Google', 'Apple', 'Huawei', 'C', 'Technology', 'Easy'),
('Who painted the Persistence of Memory?', 'Picasso', 'Dali', 'Monet', 'Matisse', 'B', 'Art', 'Hard'),
('What is the fastest fish in the ocean?', 'Tuna', 'Marlin', 'Sailfish', 'Shark', 'C', 'Animals', 'Hard');
